apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restoremodifiers.k8s.cv.io
spec:
  conversion:
    strategy: None
  group: k8s.cv.io
  names:
    kind: RestoreModifier
    listKind: RestoreModifierList
    plural: restoremodifiers
    shortNames:
    - mods
    singular: restoremodifier
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: RestoreModifier is the Schema for the restoremodifiers API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              modifiers:
                items:
                  properties:
                    action:
                      enum:
                      - Add
                      - Delete
                      - Modify
                      type: string
                    newValue:
                      type: string
                    parameters:
                      enum:
                      - Exact
                      - Contains
                      type: string
                      default: Exact
                    path:
                      type: string
                    selectorId:
                      type: string
                    value:
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - selectorId
                  type: object
                type: array
              selectors:
                items:
                  properties:
                    field:
                      properties:
                        criteria:
                          enum:
                          - Contains
                          - NotContains
                          type: string
                          default: Contains
                        exact:
                          type: boolean
                        path:
                          type: string
                        value:
                          type: string
                      type: object
                    id:
                      type: string
                    kind:
                      type: string
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                  - id
                  type: object
                type: array
            required:
            - modifiers
            - selectors
            type: object
          status:
            description: RestoreModifierStatus defines the observed state of RestoreModifier
            type: object
        type: object
    served: true
    storage: true