#
# This is sample CvTask and CvTaskSet YAML, which shows how to use commandType:Command
#
# This executes below commands inside application 'nginx-pod-1' on container 'web-server' in namespace 'nginx-prod'
# "touch /tmp/pre-from-cvtask001-command" before taking snapshots
# "touch /tmp/post-from-cvtask001-command" after taking snapshots
# Return values of executed commands will be placed at /tmp/pre.rc and /tmp/post.rc
#
apiVersion: k8s.cv.io/v1
kind: CvTask
metadata:
  name: cvtask001-command
  namespace: cv-config
spec:
  preBackupSnapshot:
    commandType: Command
    command: "touch"
    args: [ "/tmp/pre-from-cvtask001-command" ]
  postBackupSnapshot:
    commandType: Command
    command: "touch"
    args: [ "/tmp/post-from-cvtask001-command" ]
---
apiVersion: k8s.cv.io/v1
kind: CvTaskSet
metadata:
  name: cvtaskset001
  namespace: cv-config
spec:
  appName: nginx-pod-1
  appNamespace: nginx-prod
  tasks:
  - id: testid0001
    cvTaskName: cvtask001-command
    cvTaskNamespace: cv-config
    containerName: web-server
    podName: nginx-pod-1
    isDisabled: false
